#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd


# In[3]:


df = pd.read_csv('C:\\Users\\titanic.csv')
df


# In[4]:


df['Name']


# In[11]:


df[df['Age']<=25].hist(bins=60)


# In[6]:


import matplotlib.pyplot as plt


# In[7]:


pvt.loc['female', ['1st', '2nd', '3rd']]


# In[8]:


pvt = df.pivot_table(index=['Survived'], columns=['PClass'], values='Name', aggfunc='count')


# In[12]:


data = pvt.loc[1, ['1st', '2nd', '3rd']]


# In[24]:


import matplotlib.pyplot as plt

data.plot.bar()
plt.xlabel('Класс')
plt.ylabel('Кол-во выживших')

plt.show()


# In[ ]:




